#! /bin/sh
#-----------------------------------------------------------------------
#;  Copyright (C) 1998
#;  Associated Universities, Inc. Washington DC, USA.
#;
#;  This program is free software; you can redistribute it and/or
#;  modify it under the terms of the GNU General Public License as
#;  published by the Free Software Foundation; either version 2 of
#;  the License, or (at your option) any later version.
#;
#;  This program is distributed in the hope that it will be useful,
#;  but WITHOUT ANY WARRANTY; without even the implied warranty of
#;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#;  GNU General Public License for more details.
#;
#;  You should have received a copy of the GNU General Public
#;  License along with this program; if not, write to the Free
#;  Software Foundation, Inc., 675 Massachusetts Ave, Cambridge,
#;  MA 02139, USA.
#;
#;  Correspondence concerning AIPS should be addressed as follows:
#;         Internet email: aipsmail@nrao.edu.
#;         Postal address: AIPS Project Office
#;                         National Radio Astronomy Observatory
#;                         520 Edgemont Road
#;                         Charlottesville, VA 22903-2475 USA
#-----------------------------------------------------------------------
# Script to find AIPS files in the current AIPS version.
# Usage   ADVERB  <string>
# finds
#    Help files which contain <string> (case sensitive) as an adverb
#    (at the beginning of line in the inputs section).  Uses $HLPFIL.
#-----------------------------------------------------------------------

for i in `grep -l '^'$1 $HLPFIL/*.HLP` ; do
   j=`basename $i | sed -e 's/\.HLP//'`
   k=`PROG $j`
   if [ "$k" = "" ] ; then
     echo "$j (no program?)"
   else
     echo $k
   fi
   done
