#! /bin/sh
#-----------------------------------------------------------------------
#;  Copyright (C) 1995, 2003
#;  Associated Universities, Inc. Washington DC, USA.
#;
#;  This program is free software; you can redistribute it and/or
#;  modify it under the terms of the GNU General Public License as
#;  published by the Free Software Foundation; either version 2 of
#;  the License, or (at your option) any later version.
#;
#;  This program is distributed in the hope that it will be useful,
#;  but WITHOUT ANY WARRANTY; without even the implied warranty of
#;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#;  GNU General Public License for more details.
#;
#;  You should have received a copy of the GNU General Public
#;  License along with this program; if not, write to the Free
#;  Software Foundation, Inc., 675 Massachusetts Ave, Cambridge,
#;  MA 02139, USA.
#;
#;  Correspondence concerning AIPS should be addressed as follows:
#;         Internet email: aipsmail@nrao.edu.
#;         Postal address: AIPS Project Office
#;                         National Radio Astronomy Observatory
#;                         520 Edgemont Road
#;                         Charlottesville, VA 22903-2475 USA
#-----------------------------------------------------------------------
#  Script to find AIPS files in the current AIPS version.
#  Usage   AIGREP  <string> <direct> <file>
#  finds
#     files which contain <string> (case insensitive) in or below
#     directory <direct>  whose names begin with <file>
#     <direct> defaults to $AIPS_VERSION if defined or to PWD if not
#     <file> defaults to all names
#-----------------------------------------------------------------------
if [ "$2" != "" ] ; then
   FINDIR=$2
else
   if test "$AIPS_VERSION" = ""
   then
      FINDIR=`PWD`
   else
      FINDIR=$AIPS_VERSION
   fi
fi
if [ ! -d $FINDIR ] ; then
   echo "AIGREP:  Usage:  AIGREP string [directory] [file]"
   echo "AIGREP:  Arguments may need to be in quote marks"
else
   if [ "$1" != "" ] ; then
      if [ "$3" != "" ] ; then
         find $FINDIR -name $3'*' -type f -exec grep -l $1 {} \;
      else
         find $FINDIR -name '*' -type f -exec grep -l $1 {} \;
      fi
   else
      echo "AIGREP:  Usage:  AIGREP string [directory] [file]"
      echo "AIGREP:  Arguments may need to be in quote marks"
   fi
fi
