#!/bin/sh
#--------------------------------------------------------------------
#! Regenerate AREAS.CSH and AREAS.SH for Unix from $SYSAIPS/AREAS.DAT
## Shell-script
#-----------------------------------------------------------------------
#;  Copyright (C) 1995
#;  Associated Universities, Inc. Washington DC, USA.
#;
#;  This program is free software; you can redistribute it and/or
#;  modify it under the terms of the GNU General Public License as
#;  published by the Free Software Foundation; either version 2 of
#;  the License, or (at your option) any later version.
#;
#;  This program is distributed in the hope that it will be useful,
#;  but WITHOUT ANY WARRANTY; without even the implied warranty of
#;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#;  GNU General Public License for more details.
#;
#;  You should have received a copy of the GNU General Public
#;  License along with this program; if not, write to the Free
#;  Software Foundation, Inc., 675 Massachusetts Ave, Cambridge,
#;  MA 02139, USA.
#;
#;  Correspondence concerning AIPS should be addressed as follows:
#;         Internet email: aipsmail@nrao.edu.
#;         Postal address: AIPS Project Office
#;                         National Radio Astronomy Observatory
#;                         520 Edgemont Road
#;                         Charlottesville, VA 22903-2475 USA
#-----------------------------------------------------------------------
#--------------------------------------------------------------------
#  Usage: AREAS
#
#  Procedure to take the list of AIPS directories in 
#  $SYSAIPS/AREAS.DAT and, via the AREASCSH.SED and AREASSH.SED
#  "sed" scripts in $SYSUNIX, regenerate the shell scripts 
#  AREAS.CSH and AREAS.SH in $SYSUNIX.
#--------------------------------------------------------------------
#                                       Make sure files are writable
chmod +w $SYSUNIX/AREAS.CSH $SYSUNIX/AREAS.SH
#                                       Remake them.
sed -f $SYSUNIX/AREASCSH.SED $SYSAIPS/AREAS.DAT > $SYSUNIX/AREAS.CSH
sed -f $SYSUNIX/AREASSH.SED  $SYSAIPS/AREAS.DAT > $SYSUNIX/AREAS.SH
