#!/bin/sh
#-----------------------------------------------------------------------
#;  Copyright (C) 1995
#;  Associated Universities, Inc. Washington DC, USA.
#;
#;  This program is free software; you can redistribute it and/or
#;  modify it under the terms of the GNU General Public License as
#;  published by the Free Software Foundation; either version 2 of
#;  the License, or (at your option) any later version.
#;
#;  This program is distributed in the hope that it will be useful,
#;  but WITHOUT ANY WARRANTY; without even the implied warranty of
#;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#;  GNU General Public License for more details.
#;
#;  You should have received a copy of the GNU General Public
#;  License along with this program; if not, write to the Free
#;  Software Foundation, Inc., 675 Massachusetts Ave, Cambridge,
#;  MA 02139, USA.
#;
#;  Correspondence concerning AIPS should be addressed as follows:
#;         Internet email: aipsmail@nrao.edu.
#;         Postal address: AIPS Project Office
#;                         National Radio Astronomy Observatory
#;                         520 Edgemont Road
#;                         Charlottesville, VA 22903-2475 USA
#-----------------------------------------------------------------------
# EXPOSE
# --------------------------------------------------------------------
# this procedure sends a postscript file to the currently fashionable
# print que for 35 mm slides.  After a short sleep, the print que is
# checked
# 
# Last editted by glen langston on 1992 Sept 24
# --------------------------------------------------------------------
QUEUE=35mm2k
#                                       If the file exists
if test -f $1 ; then
   echo " ... Printing " $1 " on the " $QUEUE " queue  ... " 
#                                       Send file to slide maker
   lpr -P$QUEUE $1
#
   sleep 5
   echo " ... Checking the " $QUEUE " queue again ... " 
#
   lpq -P$QUEUE
else
   echo " ... FILE " $1 " NOT FOUND !!! ... " 
fi
