# Makefile for xas

#   This makefile has been tested on the following systems:
#   baboon   - Sun SparcStation 2, SunOS 4.1.2
#   rhesus   - IBM RS/6000 model 560 (AIX 3.2.2, MIT-SHM added)
#   bonobo   - Decstation 3100, Ultrix 4.0
#   pongo    - Dec Alpha AXP 3000/300, OSF-1/1.2
#   hpdemo   - HP 9000/755, HP-UX A.09.01 (X11R5)
#   tamarin  - Sun SparcStation LX, SunOS 5.2
#   tarsier  - Gateway 2000 486DX2/66 PC, Linux 0.99.12
#
#   The different settings for each architecture is indicated
#   in the comments.
#   Note for VMS, xas.h must be modified to define VMS as 1
#
#   Destination for executable.  If you are building XAS on a
#   system that has AIPS installed this should be the same as
#   the AIPS LOAD area.  MAKE SURE "LOAD" IS DEFINED FIRST!!!!!
#   Usually this is done with "source LOGIN.CSH" or ". LOGIN.SH".
#   Some implementations of make allow the use of an environmental
#   variable as shown here: check your system documentation.
DESTDIR = $(LOAD)

#   Additional include files.  Some X Window System
#   implementations do not place their include in the standard
#   Unix directory /usr/include.  The include directories should
#   be listed here, each preceded by -I.
#   On SUN4   : INCDIRS    = -I$(OPENWINHOME)/include
#   On SOL    : INCDIRS    = -I$(OPENWINHOME)/include
#   (cv sun's): INCDIRS    = -I/usr/local/include
#   On IBM    : INCDIRS    = -I/usr/include/X11
#   On HP     : INCDIRS    = -I/usr/include/X11R5
#   On DEC    : INCDIRS    = -I/usr/include/X11
#   On ALPHA  : INCDIRS    = -I/usr/include/X11
#   On LINUX  : INCDIRS    = -I/usr/include/X11
INCDIRS    = -I$(OPENWINHOME)/include

#   Library search path.  Standard Unix libraries are usually found in
#   /usr/lib; some X Window System implementations place their libraries
#   elsewhere.  These should be listed here, each preceded by -L.
#   IBM-SHR is for IBM systems shared memory.
#   On SUN4   : LIBDIRS    = -L$(OPENWINHOME)/lib
#   On SOL    : LIBDIRS    = -L$(OPENWINHOME)/lib
#   On IBM    : LIBDIRS    =
#   On IBM-SHR: LIBDIRS    = -L/usr/lpp/X11/Xamples/lib
#   On DEC    : LIBDIRS    = -L/usr/lib/X11
#   On ALPHA  : LIBDIRS    = -L/usr/lib/X11
#   On HP     : LIBDIRS    = -L/usr/lib/X11R5
#   On LINUX  : LIBDIRS    = -L/usr/X386/lib
LIBDIRS    = -L$(OPENWINHOME)/lib

#   In addition, there are apparently different requirements for
#   standard low-level libraries on the various systems and different
#   intolerance/requirement to include a library twice.
#   On SunOS 4.2 : STDLIBS  =  -lXext
#   On Solaris   : STDLIBS  =  -lsocket
#   On IBM (SHM) : STDLIBS  =  -lXextSam
STDLIBS  =  -lXext

#   The X Shared Memory Extension can significantly improve the
#   performance of XAS.  If you have the X Shared Memory
#   extension and your version of Unix supports shared memory
#   segments leave the following  definition as it is, otherwise
#   set the value to blank.  IBM X11 servers do not have it enabled
#   by default but the X server can be rebuilt to include it.
#   SHMOPT = -DUSE_SHM
#   SHMOPT =
SHMOPT =  -DUSE_SHM

#    Add OS-dependent options used inside XAS
#    On IBM    : OSOPTS = -D_AIX -D_BSD
#    On VMS    : OSOPTS = -D_VMS
#    On Unix   : OSOPTS = -D_BSD
OSOPTS = -D_BSD

#    Add local compiler/linker options here.  For example Sun 3s
#    will require a -f option to specify the floating point
#    hardware option.
#    On Debug  : LOCALOPTS = -g
#    Default   : LOCALOPTS = -O
#    On SOL    : LOCALOPTS = -O -v -K PIC -Xa
LOCALOPTS = -O

#    Your favourite C compiler
#    On SOL    : CC=/opt/SUNWspro/bin/cc
#    On SUN4   : CC=/usr/lang/cc
#    for Gnu C : CC=gcc
CC=cc

#    Do not alter anything below this line
#--------------------------------------------------------------------

.c.o :
	$(CC) $(CCOPTS) $<

CCOPTS = $(INCDIRS) $(SHMOPT) $(OSOPTS) $(LOCALOPTS) -c

OBJECTS = xas.o image.o comm.o cursor.o screen.o init.o colors.o catalog.o

install : $(DESTDIR)/XAS

$(DESTDIR)/XAS : xas
	mv xas $(DESTDIR)/XAS

all : xas

xas : $(OBJECTS)
	$(CC) $(LIBDIRS) $(LOCALOPTS) $(OBJECTS) -lXext -lX11 -lm $(STDLIBS) -o xas

xas.o   : xas.c    xas.h

image.o : image.c  xas.h

comm.o  : comm.c   xas.h

cursor.o: cursor.c xas.h

screen.o: screen.c xas.h

init.o  : init.c   xas.h  Xas.icon

colors.o: colors.c xas.h

catalog.o: catalog.c xas.h
