#!/bin/sh
##----------------------------------------------------------------------
#! prepare data areas to run CDPREP
## Shell-script
#-----------------------------------------------------------------------
#;  Copyright (C) 2005, 2017
#;  Associated Universities, Inc. Washington DC, USA.
#;
#;  This program is free software; you can redistribute it and/or
#;  modify it under the terms of the GNU General Public License as
#;  published by the Free Software Foundation; either version 2 of
#;  the License, or (at your option) any later version.
#;
#;  This program is distributed in the hope that it will be useful,
#;  but WITHOUT ANY WARRANTY; without even the implied warranty of
#;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#;  GNU General Public License for more details.
#;
#;  You should have received a copy of the GNU General Public
#;  License along with this program; if not, write to the Free
#;  Software Foundation, Inc., 675 Massachusetts Ave, Cambridge,
#;  MA 02139, USA.
#;
#;  Correspondence concerning AIPS should be addressed as follows:
#;         Internet email: aipsmail@nrao.edu.
#;         Postal address: AIPS Project Office
#;                         National Radio Astronomy Observatory
#;                         520 Edgemont Road
#;                         Charlottesville, VA 22903-2475 USA
#-----------------------------------------------------------------------
master=/home/rsync/aips/31DEC16

echo "Copy BIN areas"
mkdir BIN DA00 LINUX SUL MACPPC MACINT LNX64
cd BIN
mkdir LINUX MACPPC MACINT SUL LNX64
cp $master/LNX64/SYSTEM/MASTER/* LNX64
cp $master/LINUX/SYSTEM/MASTER/* LINUX
cp $master/MACPPC/SYSTEM/MASTER/* MACPPC
cp $master/MACINT/SYSTEM/MASTER/* MACINT
cp $master/SUL/SYSTEM/MASTER/* SUL
#
echo "Copy DA00 areas"
cd ../DA00
mkdir LINUX MACPPC MACINT SUL LNX64
cp $master/LNX64/TEMPLATE/* LNX64
cp $master/LINUX/TEMPLATE/* LINUX
cp $master/MACPPC/TEMPLATE/* MACPPC
cp $master/MACINT/TEMPLATE/* MACINT
cp $master/SUL/TEMPLATE/* SUL
#
echo "Do LINUX"
cd ../LINUX
mkdir BIN DA00 lib LIBR LOAD MEMORY
cp $master/LINUX/SYSTEM/MASTER/* BIN
cp $master/LINUX/TEMPLATE/* DA00
cp -R $master/LINUX/LIBR/INTELCMP/* lib
cp -R $master/LINUX/LIBR/* LIBR
cp -R $master/LINUX/MEMORY/* MEMORY
cp -R $master/LINUX/LOAD/* LOAD
#
echo "Do LNX64"
cd ../LNX64
mkdir BIN DA00 lib LIBR LOAD MEMORY
cp $master/LNX64/SYSTEM/MASTER/* BIN
cp $master/LNX64/TEMPLATE/* DA00
cp -R $master/LNX64/LIBR/INTELCMP/* lib
cp -R $master/LNX64/LIBR/* LIBR
cp -R $master/LNX64/MEMORY/* MEMORY
cp -R $master/LNX64/LOAD/* LOAD
#
echo "Do SUL"
cd ../SUL
mkdir BIN DA00 lib LIBR LOAD MEMORY
cp $master/SUL/SYSTEM/MASTER/* BIN
cp $master/SUL/TEMPLATE/* DA00
cp -R $master/SUL/LIBR/SUNCMP/* lib
cp -R $master/SUL/LIBR/* LIBR
cp -R $master/SUL/MEMORY/* MEMORY
cp -R $master/SUL/LOAD/* LOAD
#
echo "Do MACPPC"
cd ../MACPPC
mkdir BIN DA00 lib LIBR LOAD MEMORY
cp $master/MACPPC/SYSTEM/MASTER/* BIN
cp $master/MACPPC/TEMPLATE/* DA00
cp -R $master/MACPPC/LIBR/IBMCMP/* lib
cp -R $master/MACPPC/LIBR/* LIBR
cp -R $master/MACPPC/MEMORY/* MEMORY
cp -R $master/MACPPC/LOAD/* LOAD
#
echo "Do MACINT"
cd ../MACINT
mkdir BIN DA00 lib LIBR LOAD MEMORY
cp $master/MACINT/SYSTEM/MASTER/* BIN
cp $master/MACINT/TEMPLATE/* DA00
cp -R $master/MACINT/LIBR/INTELCMP/* lib
cp -R $master/MACINT/LIBR/* LIBR
cp -R $master/MACINT/MEMORY/* MEMORY
cp -R $master/MACINT/LOAD/* LOAD
#
echo "cdroast dirs"
cd ..
mkdir cdroast
mkdir cdroast/cdroast
mkdir cdroast/aipswork
mkdir cdroast/aipswork/cd
mkdir cdroast/aipswork/otherarch




