#!/bin/sh
#-----------------------------------------------------------------------
#;  Copyright (C) 1995
#;  Associated Universities, Inc. Washington DC, USA.
#;
#;  This program is free software; you can redistribute it and/or
#;  modify it under the terms of the GNU General Public License as
#;  published by the Free Software Foundation; either version 2 of
#;  the License, or (at your option) any later version.
#;
#;  This program is distributed in the hope that it will be useful,
#;  but WITHOUT ANY WARRANTY; without even the implied warranty of
#;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#;  GNU General Public License for more details.
#;
#;  You should have received a copy of the GNU General Public
#;  License along with this program; if not, write to the Free
#;  Software Foundation, Inc., 675 Massachusetts Ave, Cambridge,
#;  MA 02139, USA.
#;
#;  Correspondence concerning AIPS should be addressed as follows:
#;         Internet email: aipsmail@nrao.edu.
#;         Postal address: AIPS Project Office
#;                         National Radio Astronomy Observatory
#;                         520 Edgemont Road
#;                         Charlottesville, VA 22903-2475 USA
#-----------------------------------------------------------------------
# SLIDE
# --------------------------------------------------------------------
# this procedure takes x-grab encapolated postscript output and 
# formats it for the 35mm slide projector
# 
# Last editted by glen langston on 1992 Sept 18
# --------------------------------------------------------------------
#                               make sure the file exists
if test -f $1 ; then
#
  echo " ... Rescaling " $1 " and writing output to " $1.s " ..."
  echo " ... This may take a while ... "
#                               use executable if available
  if test -f $SYSLOCAL/FILLSLIDE.EXE ; then
#
     cat $1 | $SYSLOCAL/FILLSLIDE.EXE 100 > $1.s
  else
#                               else use script
     cat $1 | $SYSLOCAL/FILLSLIDE.SH > $1.s
     fi
#
  echo " ... Sending " $1.s " to the Postscript slide maker "
#
  EXPOSE $1.s
#
  echo " ... Done ... "
else
   echo " ... FILE " $1 " NOT FOUND !!! ... " 
   echo " ... Usage SLIDE <file.name> ... "
fi
